import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        
        {children}
        <footer className="bg-gray-900 text-white py-6">
  <div className="max-w-7xl mx-auto px-4 text-center space-y-2">
    <p className="text-lg font-semibold">David</p>
    <p>Email: <a href="mailto:david@example.com" className="text-blue-400 hover:underline">opabunmidavid@gmail.com</a></p>
    <p>Phone: <a href="tel:+2348087640013" className="text-blue-400 hover:underline">+234 808 764 0013</a></p>
    <p className="text-sm text-gray-400">&copy; 2025 David. All rights reserved.</p>
  </div>
</footer>
      </body>
    </html>
  );
}
